language: php

php:
  - 7.1.11
  - 7.1.0
  - 7.1
  - 7.0.25
  - 7.0.0
  - 7.0
  - 5.6.31
  - 5.6.0
  - 5.6
  - 5.5.38
  - 5.5
  - 5.4.45
  - 5.4

env:
  - WP_VERSION=latest WP_MULTISITE=0 DB=mysql
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=1
  - WP_VERSION=3.8 WP_MULTISITE=0
  - WP_VERSION=3.8 WP_MULTISITE=1
  - DB=mysql
  - DB=mariadb

os:
  - linux
  - osx
  - unix
  - windows

services:
  - mysql

addons:
  - mariadb: '5.5'
  - mariadb: '10.0'

matrix:
  allow_failures:
    - php: 7.2
    - php: 5.6.32

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;

notifications:
  email: false
